services:
  - type: web
    name: osa-hub-web
    env: docker
    plan: free
    repo: https://github.com/jamespailagao12345-ui/OSA-Central-Hub
    branch: main
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: osa-hub-db
          property: connectionString
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: "OSA Hub"
      - key: LOG_CHANNEL
        value: stack

  - type: worker
    name: osa-hub-queue
    env: docker
    plan: free
    repo: https://github.com/jamespailagao12345-ui/OSA-Central-Hub
    branch: main
    autoDeploy: true
    dockerCommand: php artisan queue:work --tries=1 --sleep=3
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: osa-hub-db
          property: connectionString
      - key: QUEUE_CONNECTION
        value: database


# Managed PostgreSQL instance

databases:
  - name: osa-hub-db
    plan: free
    databaseName: osa_hub
    user: osa_hub
